Repository DEFRA/charging-module-api, pull requests merged in 2020-08, with the labels that each got.

#50 Zero charge transaction summary info
  app/models/bill_run.js
  app/schema/pre_sroc/wrls/bill_run.js
  app/services/generate_bill_run_summary.js
  db/migrations/20200807161104-add-zero-value-line-count.js
  db/migrations/sqls/20200807161104-add-zero-value-line-count-down.sql
  db/migrations/sqls/20200807161104-add-zero-value-line-count-up.sql
  test/services/generate_bill_run_summary.test.js
Labels: enhancement

#51 Handle bill runs where all transactions have zero value
  app/jobs/file_export_job.js
  app/models/bill_run.js
  app/services/send_bill_run.js
  test/helpers/bill_run_helper.js
  test/jobs/file_export_job.test.js
  test/services/send_bill_run.test.js
Labels: enhancement

#64 Update LICENSE, README and others to meet standard
  .env.example
  .gitignore
  LICENSE
  LICENSE.md
  README.md
Labels: documentation, housekeeping

#65 Switch to using .labrc.js config file
  .gitignore
  .labrc.js
  package.json
Labels: housekeeping

#66 Add node nvm version file to project
  .nvmrc
Labels: housekeeping

#67 Add support for CI
  .env.example
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#68 Change tmpfiles folder to tmp
  .gitignore
  package.json
  tmp/.keep
Labels: housekeeping

#70 Fixed zero value transactions not being added to summary when newLicence is true
  app/services/generate_bill_run_summary.js
  test/services/generate_bill_run_summary.test.js
Labels: bug

#77 Tagged endpoints not required for pre-sroc release
  app/controllers/v1/billed_transactions_controller.js
  app/controllers/v1/sroc_calculate_charge_controller.js
  app/controllers/v1/sroc_transaction_queue_controller.js
  app/controllers/v1/transactions_controller.js
Labels: enhancement
