Repository DEFRA/charging-module-api, pull requests merged in 2020-11, with the labels that each got.

#148 Switch to using GitHub actions for CI
  .github/workflows/ci.yml
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#151 Add back check for use of `only()` in tests to CI
  .github/workflows/ci.yml
Labels: housekeeping

#153 Remove unused endpoints
  app/controllers/v1/billruns_controller.js
  app/controllers/v1/customer_changes_controller.js
  app/controllers/v1/transactions_controller.js
  app/models/bill_run.js
  app/models/customer_change.js
  app/schema/pre_sroc/wrls/bill_run.js
  app/schema/pre_sroc/wrls/bill_run_search_request.js
  app/schema/pre_sroc/wrls/customer_change.js
  app/schema/pre_sroc/wrls/index.js
  app/services/remove_bill_run_transaction.js
  app/services/remove_transaction.js
  app/services/unapprove_bill_run.js
  test/controllers/billrun_transactions_controller.test.js
  test/controllers/transactions_controller.test.js
  test/fixtures/transaction_requests.js
  test/fixtures/transactions.js
  test/helpers/bill_run_helper.js
  test/helpers/transaction_helper.js
  test/models/transaction.test.js
  test/services/unapprove_bill_run.test.js
Labels: housekeeping

#155 Move customer file endpoints to /admin/test
  app/controllers/admin/test/customer_files_controller.js
  app/plugins/router.js
Labels: housekeeping

#157 Refactor billrun & transaction tests helpers
  test/controllers/billrun_transactions_controller.test.js
  test/fixtures/bill_runs.js
  test/helpers/bill_run_helper.js
  test/helpers/database_helper.js
  test/helpers/transaction_helper.js
Labels: housekeeping

#160 Hide skipped tests
  package.json
Labels: housekeeping

#162 Exclude net zero value invoices from transaction files
  app/schema/pre_sroc/wrls/bill_run.js
  app/schema/pre_sroc/wrls/transaction.js
  app/schema/pre_sroc/wrls/transaction_file_presenter.js
  app/services/generate_bill_run_summary.js
  app/services/send_bill_run.js
  db/migrations/20201112110416-add-zero-value-invoice-flag.js
  db/migrations/sqls/20201112110416-add-zero-value-invoice-flag-down.sql
  db/migrations/sqls/20201112110416-add-zero-value-invoice-flag-up.sql
  test/helpers/bill_run_helper.js
  test/jobs/file_export_job.test.js
  test/schema/pre_sroc/wrls/transaction.test.js
  test/schema/pre_sroc/wrls/transaction_file_presenter.test.js
  test/services/generate_bill_run_summary.test.js
Labels: enhancement

#156 Create a PATCH version of billrun send endpoint
  app/controllers/v1/billruns_controller.js
  test/controllers/billruns_controller.test.js
Labels: housekeeping

#164 Underscores in urls? Oh my!
  app/controllers/admin/authorised_systems_controller.js
  app/controllers/admin/test/customer_files_controller.js
  app/controllers/v1/calculate_charge_controller.js
  app/controllers/v1/customer_changes_controller.js
  test/controllers/calculate_charge_controller.test.js
Labels: housekeeping

#166 Fix array and boolean true handling by plugins
  app/index.js
  app/plugins/disinfect.js
  app/plugins/payload_sanitiser.js
  app/plugins/unescape.js
  app/services/object_sanitising_service.js
  package-lock.json
  package.json
  test/services/object_sanitising_service.test.js
Labels: bug

#172 Prevent duplicate transactions
  app/controllers/v1/billrun_transactions_controller.js
  app/schema/pre_sroc/wrls/attribute_map.js
  app/schema/pre_sroc/wrls/transaction.js
  app/services/find_transaction_by_client_id.js
  db/migrations/20201123142133-add-client-id-to-transactions.js
  db/migrations/sqls/20201123142133-add-client-id-to-transactions-down.sql
  db/migrations/sqls/20201123142133-add-client-id-to-transactions-up.sql
  test/controllers/billrun_transactions_controller.test.js
  test/schema/pre_sroc/wrls/transaction.test.js
  test/services/find_transaction_by_client_id.test.js
Labels: enhancement
